import javax.swing.JOptionPane;
import java.util.*;
import java.util.concurrent.ThreadLocalRandom;
/*


             _  _       _           ___           _ ____      
            | || |     | |         / _ \         | |___ \     
  _   _ _ __| || |_ ___| | ___ __ | | | |_      _| | __) |___ 
 | | | | '_ \__   _/ __| |/ / '_ \| | | \ \ /\ / / ||__ <_  / 
 | |_| | | | | | || (__|   <| | | | |_| |\ V  V /| |___) / /  
  \__,_|_| |_| |_| \___|_|\_\_| |_|\___/  \_/\_/ |_|____/___| 
                                                              
                                                              

https://fuxkuhrz.wordpress.com/
https://www.facebook.com/PsynoxzhioQ
https://www.youtube.com/channel/UCNrT38ApdFrVMHjeEBu1MmQ/
https://twitter.com/_Fuxkuhrz_





*/

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class frmJFrame extends javax.swing.JFrame {

    /**
     * Creates new form frmJFrame
     */
    static void shuffleArray(int[] arg){
    // If running on Java 6 or older, use `new Random()` on RHS here
    Random rnd = ThreadLocalRandom.current();
    for (int i = arg.length - 1; i > 0; i--){
      int index = rnd.nextInt(i + 1);
      // Simple swap
      int a = arg[index];
      arg[index] = arg[i];
      arg[i] = a;
    }
  }
    
    
    
    
    
    
    String[] Question = {"11+2 ได้เท่า?", "4+6 ได้เท่า?", "1+2 ได้เท่า?", "5+2 ได้เท่า?", "50+46 ได้เท่า?"}; //โจทย์
    int choic=0; // ค่าเริ่มต้นของตัวนับโจทย์
    int p;
    int t;
    int check_ans=0;
    String[] choice_text = {"ก.", "ข.", "ค.","ง."};
    int[] ans1 = {13, 20, 6, 9}; 
    int[] ans2 = {6, 10, 50, 2};
    int[] ans3 = {3, 4, 5, 8};
    int[] ans4 = {1, 3, 5, 7};
    int[] ans5 = {95, 96, 97, 99};
    public frmJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("ย้อนกลับ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("ถัดไป");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setText("กดปุ่มถัดไปเพื่อ เริ่มตอบคำถาม");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("x");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("x");

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("x");

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setText("x");

        jButton3.setText("เช็คคำตอบ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel3.setText("ก.");

        jLabel4.setText("ค.");

        jLabel5.setText("ข.");

        jLabel6.setText("ง.");

        jLabel7.setText("คำตอบคือ:");

        jLabel8.setForeground(new java.awt.Color(0, 0, 255));

        jLabel9.setText("คุณตอบ : ");

        jLabel10.setForeground(new java.awt.Color(255, 0, 0));

        jLabel11.setText("คะแนน");

        jLabel12.setForeground(new java.awt.Color(0, 102, 51));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(34, 34, 34)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButton3)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButton4)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(30, 30, 30)
                                .addComponent(jLabel1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addGap(2, 2, 2))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)))
                .addGap(0, 40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addGap(14, 14, 14)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton3)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        if(choic == 5){
            
        JOptionPane.showMessageDialog(null,"คำถามมีแค่ 5 ข้อ ","คำเตือน",JOptionPane.WARNING_MESSAGE);
        
        }else{
        jLabel8.setText("");
        jLabel10.setText("");
        double r = Math.random() * 5;
	int rand = (int) r;
        jLabel1.setText(Question[rand]);
        int m;
        if(jLabel1.getText() == "11+2 ได้เท่า?"){
            buttonGroup1.clearSelection();
            shuffleArray(ans1);
            for(int i =0; i<4;i++){
                if(ans1[i] == 13){
                    m=i;
                    p=m;
                    t=13;
                    }
            }
            jRadioButton1.setText(String.valueOf(ans1[0]));
            jRadioButton2.setText(String.valueOf(ans1[1]));
            jRadioButton3.setText(String.valueOf(ans1[2]));
            jRadioButton4.setText(String.valueOf(ans1[3]));
            
        }
        else if(jLabel1.getText() == "4+6 ได้เท่า?"){
            buttonGroup1.clearSelection();
            shuffleArray(ans2);
            for(int i =0; i<4;i++){
                if(ans2[i] == 10){
                    m=i;
                    p=m;
                    t=10;
                }
            }
            jRadioButton1.setText(String.valueOf(ans2[0]));
            jRadioButton2.setText(String.valueOf(ans2[1]));
            jRadioButton3.setText(String.valueOf(ans2[2]));
            jRadioButton4.setText(String.valueOf(ans2[3]));
           
        }
        else if(jLabel1.getText() == "1+2 ได้เท่า?"){
            buttonGroup1.clearSelection();
            shuffleArray(ans3);
            for(int i =0; i<4;i++){
                if(ans3[i] == 3){
                    m=i;
                    p=m;
                    t=3;
                }
            }
            jRadioButton1.setText(String.valueOf(ans3[0]));
            jRadioButton2.setText(String.valueOf(ans3[1]));
            jRadioButton3.setText(String.valueOf(ans3[2]));
            jRadioButton4.setText(String.valueOf(ans3[3]));
        }
        else if(jLabel1.getText() == "5+2 ได้เท่า?"){
            buttonGroup1.clearSelection();
            shuffleArray(ans4);
            for(int i =0; i<4;i++){
                if(ans4[i] == 7){
                    m=i;
                    p=m;
                    t=7;
                }
            }
            jRadioButton1.setText(String.valueOf(ans4[0]));
            jRadioButton2.setText(String.valueOf(ans4[1]));
            jRadioButton3.setText(String.valueOf(ans4[2]));
            jRadioButton4.setText(String.valueOf(ans4[3]));
        }else{
            buttonGroup1.clearSelection();
            shuffleArray(ans5);
            for(int i =0; i<4;i++){
                if(ans5[i] == 96){
                    m=i;
                    p=m;
                    t=96;
                }
            }
            jRadioButton1.setText(String.valueOf(ans5[0]));
            jRadioButton2.setText(String.valueOf(ans5[1]));
            jRadioButton3.setText(String.valueOf(ans5[2]));
            jRadioButton4.setText(String.valueOf(ans5[3]));
        }
        
        choic++;
        jLabel2.setText(String.valueOf("ข้อที่ "+choic+"."));
        
        }
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        if(choic == 1 || choic == 0){
             JOptionPane.showMessageDialog(null,"ไม่สารถย้อนกลับได้","คำเตือน",JOptionPane.WARNING_MESSAGE);
        }else{
        jLabel8.setText("");
        jLabel10.setText("");
        double r = Math.random() * 5;
	int rand = (int) r;
        jLabel1.setText(Question[rand]);
        
      
        
        
        int m;
        if(jLabel1.getText() == "11+2 ได้เท่า?"){
            buttonGroup1.clearSelection();
            shuffleArray(ans1);
            for(int i =0; i<4;i++){
                if(ans1[i] == 13){
                    m=i;
                    p=m;
                    t=13;
                }
            }
            jRadioButton1.setText(String.valueOf(ans1[0]));
            jRadioButton2.setText(String.valueOf(ans1[1]));
            jRadioButton3.setText(String.valueOf(ans1[2]));
            jRadioButton4.setText(String.valueOf(ans1[3]));
        }
        else if(jLabel1.getText() == "4+6 ได้เท่า?"){
            buttonGroup1.clearSelection();
            shuffleArray(ans2);
            for(int i =0; i<4;i++){
                if(ans2[i] == 10){
                    m=i;
                    p=m;
                    t=10;
                }
            }
            jRadioButton1.setText(String.valueOf(ans2[0]));
            jRadioButton2.setText(String.valueOf(ans2[1]));
            jRadioButton3.setText(String.valueOf(ans2[2]));
            jRadioButton4.setText(String.valueOf(ans2[3]));
           
        }
        else if(jLabel1.getText() == "1+2 ได้เท่า?"){
            buttonGroup1.clearSelection();
            shuffleArray(ans3);
            for(int i =0; i<4;i++){
                if(ans3[i] == 3){
                    m=i;
                    p=m;
                    t=3;
                }
            }
            jRadioButton1.setText(String.valueOf(ans3[0]));
            jRadioButton2.setText(String.valueOf(ans3[1]));
            jRadioButton3.setText(String.valueOf(ans3[2]));
            jRadioButton4.setText(String.valueOf(ans3[3]));
        }
        else if(jLabel1.getText() == "5+2 ได้เท่า?"){
            buttonGroup1.clearSelection();
            shuffleArray(ans4);
            for(int i =0; i<4;i++){
                if(ans4[i] == 7){
                    m=i;
                    p=m;
                    t=7;
                }
            }
            jRadioButton1.setText(String.valueOf(ans4[0]));
            jRadioButton2.setText(String.valueOf(ans4[1]));
            jRadioButton3.setText(String.valueOf(ans4[2]));
            jRadioButton4.setText(String.valueOf(ans4[3]));
        }
        else{
            buttonGroup1.clearSelection();
            shuffleArray(ans5);
            for(int i =0; i<4;i++){
                if(ans5[i] == 96){
                    m=i;
                    p=m;
                    t=96;
                }
            }
            jRadioButton1.setText(String.valueOf(ans5[0]));
            jRadioButton2.setText(String.valueOf(ans5[1]));
            jRadioButton3.setText(String.valueOf(ans5[2]));
            jRadioButton4.setText(String.valueOf(ans5[3]));
        }
        choic--;
        jLabel2.setText(String.valueOf("ข้อที่ "+choic+"."));
        
        
               
        }
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jLabel8.setText(choice_text[p]);
        System.out.println(choice_text[p]);
        String text = GroupButtonUtils.getSelectedButtonText(buttonGroup1);
        System.out.println(text);
        System.out.println(t);
        if(text.equals(String.valueOf(t))){
            jLabel10.setText("ถูก");
            check_ans++;
            jLabel12.setText(String.valueOf(check_ans));
        }else{
            jLabel10.setText("ผิด");
        }
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    // End of variables declaration//GEN-END:variables
}
